#ifndef MODULE_DEFINITIONS_H
#define MODULE_DEFINITIONS_H

#define SWIFT_MODULE_NAME "pamm"
#define SWIFT_MODULE_VERSION "1.0.0"
#define SWIFT_MODULE_DESCRIPTION "PAMM module"

#endif // MODULE_DEFINITIONS_H
